server:
  port: 8080

spring:
   datasource:
     url: jdbc:mysql://localhost:3306/goforfood?serverTimezone=UTC&characterEncoding=utf-8
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
wx:
  url: https://api.weixin.qq.com/sns/jscode2session
  appid: wxc4e4247fd0558434
  secret: 428100113092e9240e259caa2dccf547
  grant_type: authorization_code
  #OSS
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid: LTAI5t7qAhtZAXAgovKcYs2a
  keysecret: lnWfYnopvBD1aCB7aVuunmoXj7CZZT
  bucketname: goforfood
  filehost: dish    #bucket下文件夹的路径
